AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A function is triggered every 5 mins. It messages a predefined number a predefined messasge
Resources:
  SMSPublisherFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.firsht.smspublisher.SMSPublisher::handleRequest
      Runtime: java8
      CodeUri: build/distributions/SMSPublisher.zip
      Policies: AmazonS3ReadOnlyAccess
      MemorySize: 512
      Timeout: 30
      Events:
        Schedule:
          Properties:
            Schedule: rate(5 minutes)
          Type: Schedule
      Role:
        !GetAtt PublisherLambdaRole.Arn

  PublisherLambdaRole:
        Properties:
          AssumeRolePolicyDocument:
            Statement:
            - Action: ['sts:AssumeRole']
              Effect: Allow
              Principal:
                Service: [lambda.amazonaws.com]
            Version: '2012-10-17'
          Policies:
          - PolicyDocument:
              Statement:
              - Action: ['cloudwatch:*', 'logs:*']
                Effect: Allow
                Resource: '*'
              - Action: ['SNS:Publish']
                Effect: Allow
                Resource: '*'
              Version: '2012-10-17'
            PolicyName: lambdaRolePublisher
        Type: AWS::IAM::Role