AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A function is triggered every 5 mins. It messages a predefined number a predefined messasge
Resources:
  SMSPublisherFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.firsht.smspublisher.SMSPublisher::handleRequest
      Runtime: java8
      CodeUri: build/distributions/SMSPublisher.zip
      MemorySize: 512
      Timeout: 30
      Events:
        Schedule:
          Properties:
            Schedule: rate(5 minutes)
          Type: Schedule
      Policies:
        - SNSCrudPolicy:
            TopicName:
              '*'